version: '2.1'

services:
  sfki:
    image: "sfki:0.0.2"
    container_name: "sfki"
    volumes:
      - ./config:/home/app/config
      - ./posts:/home/app/posts
    logging:
      options:
        max-size: "1G"
        max-file: "10"
    networks:
      app_net:
        ipv4_address: 172.19.0.100
    expose:
      - "3000"
    restart: always

  blog-web:
    image: 'nginx:stable-alpine'
    container_name: "blog_web"
    volumes:
      - ./blog_web:/www
      - ./config/blog_web.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - sfki
    networks:
      - app_net
    ports:
      - '80:80'
    logging:
      options:
        max-size: "1G"
        max-file: "10"
    restart: always
    command: nginx -g 'daemon off;'

networks:
  app_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16
          gateway: 172.19.0.1